name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: 10.15.0
      - name: Install deps
        run: npm ci
      - name: Run tests
        run: npm test
